# Generated by Django 6.0.4 on 2026-04-19 17:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('is_ppe', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=32)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('employee_number', models.CharField(max_length=64, unique=True)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('hire_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('director', 'Начальник монтажного объекта'), ('procurement', 'Снабженец'), ('warehouse', 'Кладовщик'), ('site_manager', 'Начальник участка'), ('accounting', 'Бухгалтерия'), ('supplier', 'Поставщик'), ('admin', 'Администратор')], default='site_manager', max_length=32)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.supplier')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PPEIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('issue_date', models.DateField()),
                ('site_name', models.CharField(max_length=255)),
                ('season', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком')], default='draft', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppe_issuances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('request_date', models.DateField()),
                ('site_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком')], default='draft', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_lines', to='core.material')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.procurementrequest')),
            ],
            options={
                'ordering': ['material__code'],
            },
        ),
        migrations.CreateModel(
            name='SMRContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('contract_date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('work_type', models.CharField(blank=True, max_length=255)),
                ('planned_volume', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('volume_unit', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком')], default='draft', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.constructionobject')),
            ],
            options={
                'ordering': ['-contract_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='core.smrcontract'),
        ),
        migrations.CreateModel(
            name='StockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('issue_date', models.DateField()),
                ('site_name', models.CharField(max_length=255)),
                ('received_by_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком')], default='draft', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_issues', to='core.smrcontract')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.stockissue')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_lines', to='core.material')),
            ],
            options={
                'ordering': ['material__code'],
            },
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('receipt_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком')], default='draft', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receipts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receipts', to='core.supplier')),
            ],
            options={
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='core.material')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.stockreceipt')),
            ],
            options={
                'ordering': ['material__code'],
            },
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='core.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(max_length=64)),
                ('doc_number', models.CharField(max_length=128)),
                ('doc_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='supplier_docs/')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком')], default='uploaded', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_documents', to='core.procurementrequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.supplier')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_supplier_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='supplier_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_receipts', to='core.supplierdocument'),
        ),
        migrations.CreateModel(
            name='SupplyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('contract_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком')], default='draft', max_length=32)),
                ('terms', models.TextField(blank=True)),
                ('related_smr_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_contracts', to='core.smrcontract')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_contracts', to='core.supplier')),
            ],
            options={
                'ordering': ['-contract_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='supply_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_documents', to='core.supplycontract'),
        ),
        migrations.CreateModel(
            name='PPEIssuanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('service_life_months', models.PositiveIntegerField(default=0)),
                ('issue_start_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('issuance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.ppeissuance')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppe_lines', to='core.material')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppe_lines', to='core.worker')),
            ],
            options={
                'ordering': ['worker__full_name', 'material__code'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(max_length=255)),
                ('work_type', models.CharField(max_length=255)),
                ('planned_volume', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('actual_volume', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('volume_unit', models.CharField(blank=True, max_length=64)),
                ('plan_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='planned', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='core.smrcontract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actual_date', '-plan_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WriteOffAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('act_date', models.DateField()),
                ('site_name', models.CharField(max_length=255)),
                ('work_type', models.CharField(max_length=255)),
                ('work_volume', models.DecimalField(decimal_places=3, max_digits=14)),
                ('volume_unit', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком')], default='draft', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_acts', to='core.smrcontract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_acts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-act_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WriteOffLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm_per_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('calculated_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('actual_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.writeoffact')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoff_lines', to='core.material')),
            ],
            options={
                'ordering': ['material__code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('doc_type', models.CharField(max_length=128)),
                ('doc_number', models.CharField(max_length=128)),
                ('doc_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('search_text', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-doc_date', '-id'],
                'indexes': [models.Index(fields=['doc_type', 'doc_date'], name='core_docume_doc_typ_75e011_idx'), models.Index(fields=['status', 'doc_date'], name='core_docume_status_1d2aaa_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id'), name='uq_document_record_entity')],
            },
        ),
        migrations.CreateModel(
            name='MaterialNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_type', models.CharField(max_length=255)),
                ('norm_per_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='core.material')),
            ],
            options={
                'ordering': ['work_type', 'material__code'],
                'constraints': [models.UniqueConstraint(fields=('work_type', 'material'), name='uq_material_norm_work_type')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_date', models.DateField()),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('location_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.PositiveBigIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.material')),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
                'indexes': [models.Index(fields=['location_name', 'movement_date'], name='core_stockm_locatio_30e645_idx'), models.Index(fields=['source_type', 'source_id'], name='core_stockm_source__7e0e1c_idx')],
            },
        ),
    ]
