# Generated by Django 6.0.4 on 2026-04-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_worklog_status_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructionobject",
            name="customer_requisites",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="smrcontract",
            name="contractor_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="smrcontract",
            name="contractor_requisites",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="smrcontract",
            name="customer_requisites",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="requisites",
            field=models.TextField(blank=True),
        ),
    ]
