# Generated by Codex on 2026-05-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_constructionobject_customer_requisites_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMaterialRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=128, unique=True)),
                ("request_date", models.DateField()),
                ("site_name", models.CharField(max_length=255)),
                ("status", models.CharField(choices=[("draft", "Черновик"), ("approval", "На утверждении"), ("approved", "Утвержден"), ("sent_accounting", "Отправлен в бухгалтерию"), ("accepted", "Принят"), ("rework", "Возвращен на доработку"), ("uploaded", "Загружен поставщиком"), ("supply_confirmed", "Подтверждение поставки")], default="draft", max_length=32)),
                ("notes", models.TextField(blank=True)),
                ("contract", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="site_material_requests", to="core.smrcontract")),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="site_material_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-request_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WorkAcceptanceAct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=128, unique=True)),
                ("act_date", models.DateField()),
                ("site_name", models.CharField(max_length=255)),
                ("work_description", models.TextField(blank=True)),
                ("accepted_volume", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("volume_unit", models.CharField(blank=True, max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("status", models.CharField(choices=[("draft", "Черновик"), ("approval", "На утверждении"), ("approved", "Утвержден"), ("sent_accounting", "Отправлен в бухгалтерию"), ("accepted", "Принят"), ("rework", "Возвращен на доработку"), ("uploaded", "Загружен поставщиком"), ("supply_confirmed", "Подтверждение поставки")], default="draft", max_length=32)),
                ("notes", models.TextField(blank=True)),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="acceptance_acts", to="core.smrcontract")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="work_acceptance_acts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-act_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SiteMaterialRequestLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="site_request_lines", to="core.material")),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="core.sitematerialrequest")),
            ],
            options={
                "ordering": ["material__code"],
            },
        ),
        migrations.AddField(
            model_name="procurementrequest",
            name="site_request",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="procurement_requests", to="core.sitematerialrequest"),
        ),
        migrations.AddField(
            model_name="stockreceipt",
            name="primary_document",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stock_receipts", to="core.primarydocument"),
        ),
        migrations.AddField(
            model_name="stockissue",
            name="site_request",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stock_issues", to="core.sitematerialrequest"),
        ),
        migrations.AddField(
            model_name="stockissue",
            name="stock_receipt",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stock_issues", to="core.stockreceipt"),
        ),
        migrations.AddField(
            model_name="ppeissuanceline",
            name="clothing_size",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="ppeissuanceline",
            name="shoe_size",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
