# Generated by Django 6.0.4 on 2026-05-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_document_flow_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком'), ('supply_confirmed', 'Подтверждение поставки')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ppeissuance',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком'), ('supply_confirmed', 'Подтверждение поставки')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='primarydocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком'), ('supply_confirmed', 'Подтверждение поставки')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком'), ('supply_confirmed', 'Подтверждение поставки')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='smrcontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком'), ('supply_confirmed', 'Подтверждение поставки')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockissue',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком'), ('supply_confirmed', 'Подтверждение поставки')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком'), ('supply_confirmed', 'Подтверждение поставки')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='supplierdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком'), ('supply_confirmed', 'Подтверждение поставки')], default='uploaded', max_length=32),
        ),
        migrations.AlterField(
            model_name='supplycontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком'), ('supply_confirmed', 'Подтверждение поставки')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='writeoffact',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком'), ('supply_confirmed', 'Подтверждение поставки')], default='draft', max_length=32),
        ),
    ]
