# Generated by Codex on 2026-05-14

from django.db import migrations, models


def seed_export_document_types(apps, schema_editor):
    DocumentType = apps.get_model("core", "DocumentType")
    DocumentType.objects.update_or_create(
        code="payment_order",
        defaults={
            "name": "Платежное поручение",
            "prefix": "PAY",
            "is_active": True,
            "available_for_upload": False,
            "available_for_generation": True,
            "requires_items": False,
            "description": "Платежное поручение на оплату поставщику.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="writeoffact",
            name="template_variant",
            field=models.CharField(
                choices=[
                    ("contract", "По договору СМР"),
                    ("production_economic", "На производственно-хозяйственные нужды"),
                ],
                default="contract",
                max_length=32,
            ),
        ),
        migrations.RunPython(seed_export_document_types, migrations.RunPython.noop),
    ]
