# Generated by Django 6.0.4 on 2026-05-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ppe_issuance_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='smrcontract',
            name='work_basis_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата основания'),
        ),
        migrations.AddField(
            model_name='smrcontract',
            name='work_basis_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='Номер основания'),
        ),
        migrations.AddField(
            model_name='smrcontract',
            name='work_basis_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Основание (тип документа)'),
        ),
        migrations.AddField(
            model_name='smrcontract',
            name='work_conditions',
            field=models.TextField(blank=True, verbose_name='Условия проведения работ'),
        ),
        migrations.AddField(
            model_name='smrcontract',
            name='work_goal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Цель работ'),
        ),
        migrations.AddField(
            model_name='smrcontract',
            name='work_object_description',
            field=models.TextField(blank=True, verbose_name='Описание объекта'),
        ),
    ]
