# Generated by Django 6.0.4 on 2026-05-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_smrcontract_work_basis_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smrcontract',
            name='customer_auth_doc',
            field=models.CharField(blank=True, default='доверенности', max_length=255, verbose_name='Документ полномочий заказчика'),
        ),
        migrations.AddField(
            model_name='smrcontract',
            name='customer_signer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО подписанта заказчика'),
        ),
        migrations.AddField(
            model_name='smrcontract',
            name='customer_signer_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность подписанта заказчика'),
        ),
    ]
