# Generated by Django 6.0.4 on 2026-05-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_smrcontract_customer_auth_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionobject',
            name='customer_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Расчётный счёт заказчика'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='customer_bank',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк заказчика'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='customer_bik',
            field=models.CharField(blank=True, max_length=32, verbose_name='БИК заказчика'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='customer_corr_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='customer_kpp',
            field=models.CharField(blank=True, max_length=32, verbose_name='КПП заказчика'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='customer_legal_address',
            field=models.CharField(blank=True, max_length=512, verbose_name='Юридический адрес заказчика'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='customer_name_short',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое наименование заказчика'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='customer_ogrn',
            field=models.CharField(blank=True, max_length=32, verbose_name='ОГРН заказчика'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='customer_okpo',
            field=models.CharField(blank=True, max_length=32, verbose_name='ОКПО заказчика'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='customer_tax_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='ИНН заказчика'),
        ),
    ]
