# Generated by Django 6.0.4 on 2026-05-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_constructionobject_customer_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppeissuance',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ppe_issuances/', verbose_name='Скан документа'),
        ),
        migrations.AddField(
            model_name='primarydocument',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='primary_documents/', verbose_name='Скан документа'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='procurement_requests/', verbose_name='Скан документа'),
        ),
        migrations.AddField(
            model_name='sitematerialrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='site_requests/', verbose_name='Скан документа'),
        ),
        migrations.AddField(
            model_name='smrcontract',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='smr_contracts/', verbose_name='Скан договора'),
        ),
        migrations.AddField(
            model_name='stockissue',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='stock_issues/', verbose_name='Скан документа'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='stock_receipts/', verbose_name='Скан документа'),
        ),
        migrations.AddField(
            model_name='supplycontract',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='supply_contracts/', verbose_name='Скан договора'),
        ),
        migrations.AddField(
            model_name='workacceptanceact',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='work_acceptances/', verbose_name='Скан документа'),
        ),
        migrations.AddField(
            model_name='writeoffact',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='writeoffs/', verbose_name='Скан документа'),
        ),
    ]
