# Generated by Django 6.0.4 on 2026-06-02 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ppeissuance_attachment_primarydocument_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeoffact',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_off_acts', to='core.smrcontract'),
        ),
    ]
