# Generated by Django 6.0.4 on 2026-06-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_writeoffact_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMRContractWorkLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=255, verbose_name='Раздел')),
                ('work_name', models.CharField(max_length=512, verbose_name='Наименование работ и затрат')),
                ('unit', models.CharField(max_length=64, verbose_name='Ед. изм.')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена единицы, руб.')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_lines', to='core.smrcontract')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
