# Generated by Django 6.0.4 on 2026-06-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_smrcontractworkline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smrcontractworkline',
            name='section',
        ),
        migrations.RemoveField(
            model_name='smrcontractworkline',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='smrcontractworkline',
            name='work_name',
        ),
        migrations.AddField(
            model_name='smrcontractworkline',
            name='work_type',
            field=models.CharField(default='', max_length=255, verbose_name='Вид работ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smrcontractworkline',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='work_type',
            field=models.CharField(default='', max_length=255, verbose_name='Вид работ'),
        ),
    ]
