# Generated by Django 6.0.4 on 2026-06-03 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_smrcontractworkline_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smrcontract',
            name='site_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный начальник участка'),
        ),
        migrations.AlterField(
            model_name='smrcontract',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='smr_contracts/', verbose_name='Локальная смета (Excel/PDF)'),
        ),
    ]
