# Generated by Django 6.0.4 on 2026-06-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_smrcontract_site_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smrcontract',
            name='scan_file',
            field=models.FileField(blank=True, null=True, upload_to='smr_contract_scans/', verbose_name='Скан подписанного договора'),
        ),
    ]
