# Generated by Django 6.0.4 on 2026-06-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_smrcontract_scan_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='min_stock',
        ),
        migrations.AddField(
            model_name='material',
            name='stock_reserve_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Норма остатка (в ед. измерения)'),
        ),
    ]
