# Generated by Django 6.0.4 on 2026-06-04 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_material_min_stock_material_stock_reserve_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('site_name', models.CharField(max_length=255)),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Окончание периода')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На утверждении'), ('approved', 'Утвержден'), ('sent_accounting', 'Отправлен в бухгалтерию'), ('accepted', 'Принят'), ('rework', 'Возвращен на доработку'), ('uploaded', 'Загружен поставщиком'), ('supply_confirmed', 'Подтверждение поставки')], default='draft', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='work_schedules/', verbose_name='Скан графика')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_schedules', to='core.smrcontract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('work_type', models.CharField(max_length=255, verbose_name='Вид работ')),
                ('stage', models.CharField(blank=True, max_length=255, verbose_name='Этап')),
                ('executor', models.CharField(blank=True, max_length=255, verbose_name='Исполнитель')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.workschedule')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
