# Generated by Django 6.0.4 on 2026-06-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_workschedule_workscheduleline'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=255, verbose_name='Вид работ')),
                ('stage_name', models.CharField(max_length=255, verbose_name='Наименование этапа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Этап работ',
                'verbose_name_plural': 'Этапы работ',
                'ordering': ['work_type', 'order', 'id'],
            },
        ),
    ]
