# Generated by Django 6.0.4 on 2026-06-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_workstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Этап'),
        ),
    ]
