# Generated by Django 6.0.4 on 2026-06-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_worklog_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workscheduleline',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата выполнения'),
        ),
        migrations.AddField(
            model_name='workscheduleline',
            name='actual_notes',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Примечание по факту'),
        ),
    ]
