# Generated by Django 6.0.4 on 2026-06-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_workscheduleline_actual_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workscheduleline',
            name='actual_start',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата начала'),
        ),
        migrations.AlterField(
            model_name='workscheduleline',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата окончания'),
        ),
    ]
