# Generated by Django 6.0.4 on 2026-06-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_workscheduleline_actual_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
