# Generated by Django 6.0.4 on 2026-06-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_worklog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.supplierdocument')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_document_lines', to='core.material')),
            ],
            options={
                'ordering': ['material__code'],
            },
        ),
    ]
