# Generated by Django 6.0.4 on 2026-06-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_supplierdocumentline'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdocument',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Ставка НДС, %'),
        ),
    ]
