# Generated by Django 6.0.4 on 2026-06-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_supplierdocument_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitematerialrequestline',
            name='reserve_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Запас'),
        ),
    ]
