# Generated by Django 6.0.4 on 2026-06-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sitematerialrequestline_reserve_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdocument',
            name='payment_order',
            field=models.FileField(blank=True, null=True, upload_to='payment_orders/', verbose_name='Платёжное поручение'),
        ),
    ]
