# Generated by Django 6.0.4 on 2026-06-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_supplierdocument_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='smrcontract',
            name='customer_signer_name_genitive',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО подписанта заказчика (родительный падеж)'),
        ),
        migrations.AddField(
            model_name='smrcontract',
            name='customer_signer_position_genitive',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность подписанта заказчика (родительный падеж)'),
        ),
    ]
