# Generated by Django 6.0.4 on 2026-06-14 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_smrcontract_customer_signer_name_genitive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.smrcontract', verbose_name='Договор СМР'),
        ),
    ]
