# Generated by Django 4.2.30 on 2026-06-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_organizationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='ogrnip',
            field=models.CharField(blank=True, help_text='Заполняется только для поставщиков-ИП.', max_length=32),
        ),
    ]
